### ISSUE TITLE
If anyone screenshare, I don't see all participants

### ISSUE THREAD

**Issue by SelimEmre** [ant-media/conference-call-application#17] opened 2022-12-02 08:52 UTC
As you can see there are 8 participants in the list of streams. But I can see 5 participants on the screen. 

<img width="1790" alt="Screenshot 2022-12-02 at 11 43 34" src="https://user-images.githubusercontent.com/9084130/205253332-9855484e-3e48-44f8-9505-81cb4bcfeed8.png">

Here is the `debugme` command results: 
```
Client Debug Info
Events:
[{"track":"ARDAMSaaudioTrack0","event":"added"},{"track":"ARDAMSaaudioTrack1","event":"added"},{"track":"ARDAMSaaudioTrack2","event":"added"},{"track":"ARDAMSvvideoTrack0","event":"added"},{"track":"ARDAMSvvideoTrack1","event":"added"},{"track":"ARDAMSvvideoTrack2","event":"added"},{"track":"ARDAMSvvideoTrack3","event":"added"},{"track":"ARDAMSvvideoTrack4","event":"added"},{"track":"ARDAMSvvideoTrack5","event":"added"}]
Participants (6):
[{"id":"umut_v7Vno6LLJT","videoLabel":"videoTrack0","track":{},"streamId":"sales","isCameraOn":true,"name":"umut","oldId":"videoTrack0"},{"id":"Oguz_HO3UabsotP","videoLabel":"videoTrack1","track":{},"streamId":"sales","isCameraOn":true,"name":"Oguz","oldId":"videoTrack1"},{"id":"Nur_LhhqsQFBmK","videoLabel":"videoTrack2","track":{},"streamId":"sales","isCameraOn":true,"name":"Nur","oldId":"Hamit_5xmL0lbHNk"},{"id":"burak_MClCIdVJ8O","videoLabel":"videoTrack3","track":{},"streamId":"sales","isCameraOn":true,"name":"burak","oldId":"videoTrack3"},{"id":"Hamit_5xmL0lbHNk","videoLabel":"videoTrack4","track":{},"streamId":"sales","isCameraOn":true,"name":"Hamit","oldId":"harun_vBXABycjns"},{"id":"Alper_hCoQguAduU","videoLabel":"videoTrack5","track":{},"streamId":"sales","isCameraOn":true,"name":"Alper","oldId":"videoTrack5"}]
----------------------
Server Debug Info
Self Track Id:Selimmm_tyQVaeSJUM

Video Track Map:
Alper_hCoQguAduU:true
harun_vBXABycjns:true
burak_MClCIdVJ8O:true
Selimmm_tyQVaeSJUM:false
Nur_LhhqsQFBmK:true
Oguz_HO3UabsotP:true
Hamit_5xmL0lbHNk:true
umut_v7Vno6LLJT:true

Video Track Assignments (6/6)
{label:videoTrack0,assigned stream id:umut_v7Vno6LLJT,reserved:false,prevAssignedStreamId:null,lastSentTime:1669970560937,ts:2582330000000,offset:0,keyFrameSent:true,}
{label:videoTrack1,assigned stream id:Oguz_HO3UabsotP,reserved:true,prevAssignedStreamId:null,lastSentTime:1669970625436,ts:2606360000000,offset:5550000000,keyFrameSent:true,}
{label:videoTrack2,assigned stream id:Nur_LhhqsQFBmK,reserved:false,prevAssignedStreamId:null,lastSentTime:1669970627781,ts:2565000000000,offset:3090000000,keyFrameSent:true,}
{label:videoTrack3,assigned stream id:burak_MClCIdVJ8O,reserved:false,prevAssignedStreamId:null,lastSentTime:1669970626801,ts:2554710000000,offset:0,keyFrameSent:true,}
{label:videoTrack4,assigned stream id:Hamit_5xmL0lbHNk,reserved:false,prevAssignedStreamId:null,lastSentTime:1669970402650,ts:2604150000000,offset:-108120000000,keyFrameSent:true,}
{label:videoTrack5,assigned stream id:Alper_hCoQguAduU,reserved:true,prevAssignedStreamId:null,lastSentTime:1669970621837,ts:2533940000000,offset:250000000,keyFrameSent:true,}

Audio Track Assignments (3/3)
{label:audioTrack0,assigned stream id:Nur_LhhqsQFBmK,currentLevel:9,score:155}
{label:audioTrack1,assigned stream id:Oguz_HO3UabsotP,currentLevel:1,score:1027}
{label:audioTrack2,assigned stream id:burak_MClCIdVJ8O,currentLevel:1,score:1311}
```

Best Regards,
Selim

**Comment by burak-58** [comment] 2023-02-20 15:59
I think the problem is 1 other text, it should be 4 others.

**Comment by mustafaboleken** [comment] 2024-03-19 10:48
It's fixed in the latest version. I'm closing this issue.

**Closed by mustafaboleken** 2024-03-19 10:48 UTC
