### ISSUE TITLE
Data Channel keeps sending last data message

### ISSUE THREAD

**Issue by ScottStick** [ant-media/conference-call-application#153] opened 2023-09-07 03:33 UTC
When I'm sending data arrays (not text strings) over the data channel, the last array that was sent keeps getting sent over and over again at a consistent interval. 

I cannot find where webRTCAdaptor.sendData() uses an interval, but clearly this behaviour doesn't happen when sending text messages over the data channel. How can I stop/cancel the interval so that each array is sent once only?

**Comment by mekya** [comment] 2023-09-11 09:15
Hi @ScottStick ,

Thank you for this issue. This is something important. I've set its priority to high in the project. 

Thank you

Regards

**Comment by ScottStick** [comment] 2023-09-11 23:12
Hi Oz,

Thank you for your replies to my issues and especially for letting me know that the best way to interact with you is via the ***@***.******@***.***> address. I will definitely use that from now on.

Please let me know if you require any further information to assist you with the questions I’ve raised – I’m more than happy to help if I can, though I must admit that I’m still learning the correct way to do things using ReactJS and Material UI.

Kind regards,

Scott

[Logo  Description automatically generated with medium confidence]<https://www.montysp.com.au/>

[A blue and white logo  Description automatically generated with low confidence]<https://www.dciatechnologies.com.au/>

***@***.***
Scott Stickland
PhD Music (Newcastle); MMusTech (Newcastle); BEd(Sec) – Music (Melbourne)

Phone: 613 9461-1518
Mobile: 61478 221-209
Email: ***@***.******@***.***>

www.montysp.com.au<http://www.montysp.com.au/>

[A blue circle with white letters on it  Description automatically generated with medium confidence]<https://www.linkedin.com/in/scott-stickland-phduon/>  [THE NEW LATEST FACEBOOK LOGO PNG TRANSPARENT 2022] <https://www.facebook.com/sstickland70/>    [1 - Researchgate Logo Circle, HD Png Download , Transparent ...] <https://www.researchgate.net/profile/Scott-Stickland>   [Google Scholar Academic journal Google logo Education, google, text,  trademark png | PNGEgg] <https://scholar.google.com.au/citations?user=q-eB4_8AAAAJ&hl=en>


Une chose qui m’humilie profondément est de voir que le génie humain a des limites, quand la bêtise humaine n’en a pas. Alexandre Dumas

**Comment by mustafaboleken** [comment] 2023-09-18 11:22
Hi @ScottStick,

Can you please test it again with the following snapshots? It looks like the problem is solved.

https://drive.google.com/file/d/1IyGIU2OVx7whhQSUVJ4u0nH9ZWydRkih/view?usp=sharing
https://www.npmjs.com/package/@antmedia/webrtc_adaptor/v/2.7.0-SNAPSHOT-2023-Sep-17-10-28

**Comment by mekya** [comment] 2023-09-25 11:50
Closing this issue for the inacitivity. Please feel free to re-open if it does not work for you

**Closed by mekya** 2023-09-25 11:50 UTC
